[project]
name = "MLOps_course_AGH_homework_12"
version = "1.0.0"
description = ""

requires-python = "==3.11.*"

dependencies = [
    "apache-airflow[celery,postgres,standard,uv]==3.1.5",
    "apache-airflow-providers-amazon[s3fs]",
    "twelvedata",
]

[dependency-groups]
dev = [
    "ruff"
]

airflow_common = [
    "apache-airflow[celery,postgres,standard,uv,cloudpickle,s3fs]==3.1.5",
    "apache-airflow-providers-amazon[s3fs]",
    "requests",
    "s3fs",
    "polars",
    "scikit-learn",
]



